// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(3662569824);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(2248171277).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.StatusInfo | null>}
 */
export function GetStatus() {
    return $Call.ByID(3763388456).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopConfig | null>}
 */
export function LoadConfig() {
    return $Call.ByID(2354385772).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(1600263929);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup() {
    return $Call.ByID(4238615284);
}

/**
 * @param {$models.DesktopConfig | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(833119349, cfg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartTunnel() {
    return $Call.ByID(4029424060);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopTunnel() {
    return $Call.ByID(1462812540);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.StatusInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.DesktopConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
