// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GTApp from "./gtapp.js";
export {
    GTApp
};

export {
    DesktopConfig,
    DesktopService,
    DesktopURL,
    StatusInfo
} from "./models.js";
