// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DesktopConfig {
    /**
     * Creates a new DesktopConfig instance.
     * @param {Partial<DesktopConfig>} [$$source = {}] - The source object to create the DesktopConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ConfigType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DesktopService[] | undefined}
             */
            this["Services"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["Secret"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ReconnectDelay"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["Remote"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["RemoteSTUN"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["RemoteAPI"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["RemoteCert"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["RemoteCertInsecure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["RemoteConnections"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["RemoteIdleConnections"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["RemoteTimeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["WebRTCLogLevel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["LogFile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["LogFileMaxSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["LogFileMaxCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["LogLevel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["OpenBBR"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["Extras"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField19_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Services" in $$parsedSource) {
            $$parsedSource["Services"] = $$createField1_0($$parsedSource["Services"]);
        }
        if ("Remote" in $$parsedSource) {
            $$parsedSource["Remote"] = $$createField5_0($$parsedSource["Remote"]);
        }
        if ("RemoteSTUN" in $$parsedSource) {
            $$parsedSource["RemoteSTUN"] = $$createField6_0($$parsedSource["RemoteSTUN"]);
        }
        if ("Extras" in $$parsedSource) {
            $$parsedSource["Extras"] = $$createField19_0($$parsedSource["Extras"]);
        }
        return new DesktopConfig(/** @type {Partial<DesktopConfig>} */($$parsedSource));
    }
}

export class DesktopService {
    /**
     * Creates a new DesktopService instance.
     * @param {Partial<DesktopService>} [$$source = {}] - The source object to create the DesktopService.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["HostPrefix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["RemoteTCPPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["RemoteTCPRandom"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DesktopURL | undefined}
             */
            this["LocalURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["LocalTimeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["UseLocalAsHTTPHost"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["Extras"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopService}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LocalURL" in $$parsedSource) {
            $$parsedSource["LocalURL"] = $$createField3_0($$parsedSource["LocalURL"]);
        }
        if ("Extras" in $$parsedSource) {
            $$parsedSource["Extras"] = $$createField6_0($$parsedSource["Extras"]);
        }
        return new DesktopService(/** @type {Partial<DesktopService>} */($$parsedSource));
    }
}

export class DesktopURL {
    /**
     * Creates a new DesktopURL instance.
     * @param {Partial<DesktopURL>} [$$source = {}] - The source object to create the DesktopURL.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["URL"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopURL instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopURL}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopURL(/** @type {Partial<DesktopURL>} */($$parsedSource));
    }
}

export class StatusInfo {
    /**
     * Creates a new StatusInfo instance.
     * @param {Partial<StatusInfo>} [$$source = {}] - The source object to create the StatusInfo.
     */
    constructor($$source = {}) {
        if (!("isRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRunning"] = false;
        }
        if (!("serverAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverAddr"] = "";
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("pingMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pingMs"] = 0;
        }
        if (!("speedUp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speedUp"] = "";
        }
        if (!("speedDown" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speedDown"] = "";
        }
        if (!("activeSvc" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["activeSvc"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusInfo}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("activeSvc" in $$parsedSource) {
            $$parsedSource["activeSvc"] = $$createField6_0($$parsedSource["activeSvc"]);
        }
        return new StatusInfo(/** @type {Partial<StatusInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DesktopService.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = DesktopURL.createFrom;
