version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "GT-Desktop"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  PACKAGE_MANAGER: npm

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  package:
    summary: Packages the application
    cmds:
      - task: "{{OS}}:package"
